# Generated by Django 4.2.7 on 2025-07-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_studentrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentrecord',
            old_name='department',
            new_name='programme',
        ),
        migrations.RemoveField(
            model_name='studentrecord',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='studentrecord',
            name='other_names',
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='status',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
